# Lab 4 - GraphX
In this lab we use GraphX to cluster music songs according to the tags attached to each song. The datasets that we are working is available under the folder `data`, and also can be downloaded from [here](http://www.cs.cornell.edu/~shuochen/lme/data_page.html). The datasets consist of the following files:
* `song_hash.txt`: this file maps a song ID to its title and artist.
  + Each line corresponds to one song, and has the format called `Integer_ID\tTitle\tArtist\n`.
* `tag_hash.txt`: this one maps a tag ID to its name.
  + Each line corresponds to one song, and has the format called `Integer_ID, Name\n`.
* `tags.txt`: this file includes the social tags by using the integer ID to represent songs.
  + The tag data file has the same number of lines as the total number of songs. Each line consists of the IDs of the tags for a song, represented by integers, and separated by space. If a song does not have a tag, its line is just a #. Note that for the tag file, there is no space at the end of each line.

### Load the data into a Spark graph property
Let's start by loading the data into a Spark graph property. To do this, wee define a case class `Song`, with three attributes: `title`, `artist`, and a set of `tags`.

In [1]:
import scala.io.Source
import org.apache.spark.rdd.RDD
import org.apache.spark.graphx._
import org.apache.spark.mllib.clustering.PowerIterationClustering

case class Song(title: String, artist: String, tags: Set[String])

defined class Song


Now, import the songs from the dataset file `song_hash.txt` into `RDD[(VertexId, Song)]`, called `songs`, and initialize each song with an empty set of tags. You should see the following lines, if you run `songs.take(5).foreach(println)`:
```
(0,Song(Gucci Time (w\/ Swizz Beatz),Gucci Mane,Set()))
(1,Song(Aston Martin Music (w\/ Drake & Chrisette Michelle),Rick Ross,Set()))
(2,Song(Get Back Up (w\/ Chris Brown),T.I.,Set()))
(3,Song(Hot Toddy (w\/ Jay-Z & Ester Dean),Usher,Set()))
(4,Song(Whip My Hair,Willow,Set()))
```

In [2]:
val fileName = "data/song_hash.txt"

var songs: RDD[(VertexId, Song)] = sc.textFile(fileName).map(x=>x.split("\t")).map(x=>(x(0).toInt, Song(x(1),x(2),Set())) )
// songs.collect.map(println)

fileName = data/song_hash.txt
songs = MapPartitionsRDD[3] at map at <console>:37


MapPartitionsRDD[3] at map at <console>:37

Then, create a graph property called `graphFromSongs`, whose nodes are the songs, i.e., `Graph[Song, Int]`. It will not add any edges into the graph at first. If you print the vertices of the `graphFromSongs` by calling `graphFromSongs.vertices.take(5).foreach(println)`, you should see something as below:
```
(1084,Song(Tequila Sunrise,Fiji,Set()))
(1410,Song(The Sweetest Taboo,Sade,Set()))
(3066,Song(Bow Chicka Wow Wow,Mike Posner,Set()))
(1894,Song(Love Your Love The Most,Eric Church,Set()))
(466,Song(Stupify,Disturbed,Set()))
```

In [3]:
val graphFromSongs: Graph[Song, Int] = Graph(songs, sc.parallelize(Array(Edge[Int]())), Song("","",Set()) )

graphFromSongs.vertices.take(5).foreach(println)

(1084,Song(Tequila Sunrise,Fiji,Set()))                                         
(1410,Song(The Sweetest Taboo,Sade,Set()))
(3066,Song(Bow Chicka Wow Wow,Mike Posner,Set()))
(1894,Song(Love Your Love The Most,Eric Church,Set()))
(466,Song(Stupify,Disturbed,Set()))


graphFromSongs = org.apache.spark.graphx.impl.GraphImpl@47805cee


org.apache.spark.graphx.impl.GraphImpl@47805cee

### Extract the features of nodes
Now, let's join the tags from the dataset called `tags.txt` into the nodes. To do this, we first need to create `tagRDD`, which is in form of `RDD[(VertexId, Set[String])]`. We then join it with `graphFromSong`. For now, we have only the mapping between the song ID and the set of tag IDs in our `tagRDD`. If we print the first five items of the `tagRDD` we should see the following lines:
```
(0,Set(115, 173))
(1,Set(62, 88, 110, 90, 123, 155, 173, 14, 190, 214, 115, 27))
(2,Set(115, 173))
(3,Set(2, 72, 173))
(4,Set(62, 88, 141, 107, 24, 155, 72, 6, 126, 173, 190, 115, 2, 52))
```

In [4]:
val tagFile = "data/tags.txt"

val tagIter: Iterator[(VertexId, Set[String])] = Source.fromFile(tagFile).getLines.zipWithIndex.map { x => (x._2, x._1.split(" ").toSet) }

val tagRDD = sc.parallelize(tagIter.toSeq)

tagFile = data/tags.txt
tagIter = non-empty iterator
tagRDD = ParallelCollectionRDD[17] at parallelize at <console>:37


ParallelCollectionRDD[17] at parallelize at <console>:37

In [5]:
tagRDD.take(5).map(println)

(0,Set(115, 173))
(1,Set(62, 88, 110, 90, 123, 155, 173, 14, 190, 214, 115, 27))
(2,Set(115, 173))
(3,Set(2, 72, 173))
(4,Set(62, 88, 141, 107, 24, 155, 72, 6, 126, 173, 190, 115, 2, 52))


[(), (), (), (), ()]

What we want is to extract the tag names from `tag_hash.txt` given the tag ID. We can now call `joinVertices` on `graphFromSongs`, and pass the RDD of tags `tagRDD` with a function that extracts the tags. Note that in the dataset called `tags.txt`, a `#` assigned next to the song ID means that no tag is associated with that song. In such a case, we simply return the initial song with an empty tag, otherwise, we add the set of tags into the song. Below, you can see an example output if you run `songsNtags.vertices.take(5).foreach(println)`:
```
(1084,Song(Tequila Sunrise,Fiji,Set()))
(1410,Song(The Sweetest Taboo,Sade,Set(beautiful, 1980s, 80's, rock, sexy, favorite, female vocalist, smooth, female, pop, best, 80s, soul, easy listening, classic, chillout, urban, lounge, romantic, soft, singer-songwriter, lovely, chill, dance, love songs, mellow, love, jazz, female vocals, british, female vocalists, rnb, smooth jazz, favorites, ballad, relax, adult contemporary, great, melancholy, relaxing)))
(3066,Song(Bow Chicka Wow Wow,Mike Posner,Set(sexy, smooth, male vocalists, pop, <3, hip-hop, love song, wdzh-fm, awesome, easy listening, love at first listen, r&b, electronic, love songs, love, american, 2010s, nostalgic, rnb, favorites, wkqi-fm)))
(1894,Song(Love Your Love The Most,Eric Church,Set(beautiful, makes me smile, fav, pop, modern country, country, great song, love songs, favourite songs, usa, love, favorites, male country, my favorite)))
(466,Song(Stupify,Disturbed,Set(punk rock, rock, 90s, alternative metal, favorite, favourite, favorite songs, good, nu metal, 00s, angry, progressive rock, awesome, male vocalist, hardcore, sex, alternative, favs, heavy, 2000s, heavy metal, classic rock, hard rock, alternative rock, american, female vocalists, catchy, favorites, metal, my music, nu-metal, aitch)))
```

In [6]:
val songsNtags = graphFromSongs.joinVertices(tagRDD) {
  (id, s, ks) => ks.toList match {
    case List("#") => s
    case _ => {
      val taghashFile = "data/tag_hash.txt"
      val tags: Map[Int, String] = Source.fromFile(taghashFile).getLines().map(_.split(", ")).map(x => (x(0).toInt, x(1))).toMap
      val songTags = ks.map(_.toInt).flatMap(tags.get)
      Song(s.title, s.artist, songTags.toSet)
    }
  }
}

songsNtags.vertices.take(3).foreach(println)

(1084,Song(Tequila Sunrise,Fiji,Set()))
(1410,Song(The Sweetest Taboo,Sade,Set(beautiful, 1980s, 80's, rock, sexy, favorite, female vocalist, smooth, female, pop, best, 80s, soul, easy listening, classic, chillout, urban, lounge, romantic, soft, singer-songwriter, lovely, chill, dance, love songs, mellow, love, jazz, female vocals, british, female vocalists, rnb, smooth jazz, favorites, ballad, relax, adult contemporary, great, melancholy, relaxing)))
(3066,Song(Bow Chicka Wow Wow,Mike Posner,Set(sexy, smooth, male vocalists, pop, <3, hip-hop, love song, wdzh-fm, awesome, easy listening, love at first listen, r&b, electronic, love songs, love, american, 2010s, nostalgic, rnb, favorites, wkqi-fm)))


songsNtags = org.apache.spark.graphx.impl.GraphImpl@1f214b72


org.apache.spark.graphx.impl.GraphImpl@1f214b72

### Define a similarity measure between two nodes
Now, let's measure the similarity between two songs using the *Jaccard metric*, which is the ratio of the number of common tags between two songs, and their total number of tags. If none of the songs is tagged, we assume that their similarity score is zero. For this, we define the `similarity` method as below.

In [7]:
def similarity(one: Song, other: Song): Double = {
  val numCommonTags = (one.tags intersect other.tags).size
  val numTotalTags = (one.tags union other.tags).size
  if (numTotalTags > 0)
    numCommonTags.toDouble / numTotalTags.toDouble
  else 
    0.0
}

similarity: (one: Song, other: Song)Double


### Creating an affinity matrix
Now, we need to calculate the similarity between each pair of songs in our database. If there are 1,000 songs, we will have to compute, and store, one million similarity scores. What if we had 1,000,000 songs? Obviously, computing similarities between every pair will be inefficient. Instead, we can restrict this to the songs that have a relatively high similarity score. At the end of the day, we want to cluster songs that are similar. Therefore, we will filter the nodes with the following function.

In [8]:
def quiteSimilar(one: Song, other: Song, threshold: Double): Boolean = {
  val commonTags = one.tags.intersect(other.tags)
  val combinedTags = one.tags.union(other.tags)
  commonTags.size > combinedTags.size * threshold
}

quiteSimilar: (one: Song, other: Song, threshold: Double)Boolean


We define a function to remove the duplicate songs in our graph data.

In [9]:
def differentSong(one: Song, other: Song): Boolean = one.title != other.title || one.artist != other.artist

differentSong: (one: Song, other: Song)Boolean


With these two functions, we can now create `RDD[Edge[Double]]` that will contain a similarity measure between the nodes that are quite similar. A simple check `similarConnections.count` shows that we only need to store 1,506 similarity scores instead of 10 million.

### Note from the group
the computation of the cartesian was too intense for our laptop. Also, we did not find an "easy" way to increase the memory toree uses for the driver and executor, so we were stuck at 256MB. Apparently it is not enough to store the cartesian and a lot of disk I/O was in place.
We then implemented a nasty workaround, which is filtering by the artists we already know were in the final result.
This worked.
Nevertheless, **at the end of this notebook**, in the appendix, there is a "more elegant" workaround that uses the simmetric property of the similarity to avoid computing it for the whole matrix but only for half of it. It also excludes the diagonal (same songs).

In [54]:
// Somehow if we define the function outside of this block we got a TaskNotSearilizable Exception
def similarity(one: Song, other: Song): Double = {
  val numCommonTags = (one.tags intersect other.tags).size
  val numTotalTags = (one.tags union other.tags).size
  if (numTotalTags > 0)
    numCommonTags.toDouble / numTotalTags.toDouble
  else 
    0.0
}

def quiteSimilar(one: Song, other: Song, threshold: Double): Boolean = {
  val commonTags = one.tags.intersect(other.tags)
  val combinedTags = one.tags.union(other.tags)
  commonTags.size > combinedTags.size * threshold
}

def differentSong(one: Song, other: Song): Boolean = one.title != other.title || one.artist != other.artist


// First, get the songs with tags
songs = songsNtags.vertices

// Then, compute the similarity between each pair of songs with a similarity score larger than 0.7
val similarConnections: RDD[Edge[Double]] = {
    // the computation of the cartesian product is really expensive
    // so we decided to use only the songs with the authors that appears in the final result.
    // see at the end of the notebook for a "more elegant" workaround
  val good_artistis = Array("Drake","Lloyd Banks","Easton Corbin","The Band Perry","Fee","Jars Of Clay","MercyMe")
  val ss = songs.filter(x => good_artistis.contains(x._2.artist)).cartesian(songs)
    
//   val ss = songs.cartesian(songs) // this is really expensive to compute, also we do not really need all the matrix
    // since similarity is a simmetric (but not formally a distance because d(x,x) = 1/2 => != 0)
    // so we could think of a method to produce only half of the matrix and excluding directly the diagonal
    // TBC...
    
  // similarSongs are the songs with a similarity score larger than 0.7
  // Note that not compare a song with itself (use the differentSong method)
  val similarSongs = ss.filter { x => if (differentSong(x._1._2, x._2._2)) quiteSimilar(x._1._2, x._2._2, 0.7) else false }
    
  // Now compute the Jaccard metric for the similarSongs. The result should ba an Edge for each pair of songs
  // with the vertexIds at the two ends, and the Jaccard values as the edge value.
  similarSongs.map { p => {
    val jacIdx = similarity(p._1._2, p._2._2)
    Edge(p._1._1, p._2._1, jacIdx)}
  }
}

songs = VertexRDDImpl[20] at RDD at VertexRDD.scala:57
similarConnections = MapPartitionsRDD[228] at map at <console>:90


similarity: (one: Song, other: Song)Double
quiteSimilar: (one: Song, other: Song, threshold: Double)Boolean
differentSong: (one: Song, other: Song)Boolean


MapPartitionsRDD[228] at map at <console>:90

Let's create our similarity graph `similarByTagsGraph`.

In [55]:
val similarByTagsGraph = Graph(songs, similarConnections)

similarByTagsGraph = org.apache.spark.graphx.impl.GraphImpl@5e4675f0


org.apache.spark.graphx.impl.GraphImpl@5e4675f0

Some of our songs have very few tags, so let's filter those out and keep the songs with more than five tags.

In [56]:
val similarHighTagsGraph = similarByTagsGraph.subgraph(vpred = (id,attr) => attr.tags.size > 5)

similarHighTagsGraph = org.apache.spark.graphx.impl.GraphImpl@27c089b5


org.apache.spark.graphx.impl.GraphImpl@27c089b5

Let's look closer into the graph.

In [57]:
similarHighTagsGraph.triplets.take(6).foreach(t => println(t.srcAttr + " ~~~ " + t.dstAttr + " => " + t.attr))

Song(Fancy (w\/ T.I. & Swizz Beatz),Drake,Set(rap, wdzh-fm, 2010, hip hop, wjlb-fm, whtd-fm, wkqi-fm)) ~~~ Song(Any Girl (w\/ Lloyd),Lloyd Banks,Set(rap, wdzh-fm, hip hop, wjlb-fm, whtd-fm, wkqi-fm)) => 0.8571428571428571
Song(Roll With It,Easton Corbin,Set(new country, modern country, country, great song, 2010, my favorite)) ~~~ Song(You Lie,The Band Perry,Set(new country, modern country, country, great song, female vocalists, my favorite)) => 0.7142857142857143
Song(Any Girl (w\/ Lloyd),Lloyd Banks,Set(rap, wdzh-fm, hip hop, wjlb-fm, whtd-fm, wkqi-fm)) ~~~ Song(Fancy (w\/ T.I. & Swizz Beatz),Drake,Set(rap, wdzh-fm, 2010, hip hop, wjlb-fm, whtd-fm, wkqi-fm)) => 0.8571428571428571
Song(Any Girl (w\/ Lloyd),Lloyd Banks,Set(rap, wdzh-fm, hip hop, wjlb-fm, whtd-fm, wkqi-fm)) ~~~ Song(I'm Going In (w\/ Young Jeezy & Lil Wayne),Drake,Set(rap, hip-hop, wdzh-fm, wjlb-fm, whtd-fm, wkqi-fm)) => 0.7142857142857143
Song(Everything Falls,Fee,Set(rock, worship, christian, contemporary christian, go

You should see the following output:
```
Song(Fancy (w\/ T.I. & Swizz Beatz),Drake,Set(rap, wdzh-fm, 2010, hip hop, wjlb-fm, whtd-fm, wkqi-fm)) ~~~ Song(Any Girl (w\/ Lloyd),Lloyd Banks,Set(rap, wdzh-fm, hip hop, wjlb-fm, whtd-fm, wkqi-fm)) => 0.8571428571428571
Song(Roll With It,Easton Corbin,Set(new country, modern country, country, great song, 2010, my favorite)) ~~~ Song(You Lie,The Band Perry,Set(new country, modern country, country, great song, female vocalists, my favorite)) => 0.7142857142857143
Song(Any Girl (w\/ Lloyd),Lloyd Banks,Set(rap, wdzh-fm, hip hop, wjlb-fm, whtd-fm, wkqi-fm)) ~~~ Song(Fancy (w\/ T.I. & Swizz Beatz),Drake,Set(rap, wdzh-fm, 2010, hip hop, wjlb-fm, whtd-fm, wkqi-fm)) => 0.8571428571428571
Song(Any Girl (w\/ Lloyd),Lloyd Banks,Set(rap, wdzh-fm, hip hop, wjlb-fm, whtd-fm, wkqi-fm)) ~~~ Song(I'm Going In (w\/ Young Jeezy & Lil Wayne),Drake,Set(rap, hip-hop, wdzh-fm, wjlb-fm, whtd-fm, wkqi-fm)) => 0.7142857142857143
Song(Everything Falls,Fee,Set(rock, worship, christian, contemporary christian, good stuff, christian rock)) ~~~ Song(Needful Hands,Jars Of Clay,Set(rock, worship, christian, contemporary christian, christian rock, favorites)) => 0.7142857142857143
Song(Bring The Rain,MercyMe,Set(rock, worship, christian, contemporary christian, uplifting, christian rock, powerful, favorites)) ~~~ Song(Needful Hands,Jars Of Clay,Set(rock, worship, christian, contemporary christian, christian rock, favorites)) => 0.75
```
We can see that "Fancy" by "Drake" is similar to "Any Girl" by "Lloyd Banks". Of course, they are rap songs. 

# Appendix
## Delirious part trying to avoid computing the whole cartesian

In [66]:
val asd = sc.parallelize("A B C D E".split(" "))
asd.cartesian(asd).collect.map(println)

(A,A)
(A,B)
(A,C)
(A,D)
(A,E)
(B,A)
(B,B)
(B,C)
(B,D)
(B,E)
(C,A)
(C,B)
(C,C)
(C,D)
(C,E)
(D,A)
(E,A)
(D,B)
(E,B)
(D,C)
(E,C)
(D,D)
(D,E)
(E,D)
(E,E)


asd = ParallelCollectionRDD[255] at parallelize at <console>:35


[(), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), ()]

In [75]:
val asdWithIndex = asd.zipWithIndex()
asdWithIndex.collect.map(println)

(A,0)
(B,1)
(C,2)
(D,3)
(E,4)


asdWithIndex = ZippedWithIndexRDD[260] at zipWithIndex at <console>:37


[(), (), (), (), ()]

In [78]:
asdWithIndex.cartesian(asdWithIndex).filter(x => x._1._2 < x._2._2).collect.map(println)

((A,0),(B,1))
((A,0),(C,2))
((A,0),(D,3))
((A,0),(E,4))
((B,1),(C,2))
((B,1),(D,3))
((B,1),(E,4))
((C,2),(D,3))
((C,2),(E,4))
((D,3),(E,4))


[(), (), (), (), (), (), (), (), (), ()]

In [79]:
asdWithIndex.cartesian(asdWithIndex).filter(x => x._1._2 < x._2._2).map(x => (x._1._1,x._2._1)  ).collect.map(println)

(A,B)
(A,C)
(A,D)
(A,E)
(B,C)
(B,D)
(B,E)
(C,D)
(C,E)
(D,E)


[(), (), (), (), (), (), (), (), (), ()]

This **does not** solve the problem of computing the cartesian, but will reduce of more than 1/2 the computaion of the similarity index and no need to check if the songs are the same. Also it is a good idea to filter the vertex with less than five tags BEFORE computing the cartesian
Lets try it...

In [84]:
// Somehow if we define the function outside of this block we got a TaskNotSearilizable Exception
def similarity(one: Song, other: Song): Double = {
  val numCommonTags = (one.tags intersect other.tags).size
  val numTotalTags = (one.tags union other.tags).size
  if (numTotalTags > 0)
    numCommonTags.toDouble / numTotalTags.toDouble
  else 
    0.0
}

def quiteSimilar(one: Song, other: Song, threshold: Double): Boolean = {
  val commonTags = one.tags.intersect(other.tags)
  val combinedTags = one.tags.union(other.tags)
  commonTags.size > combinedTags.size * threshold
}

def differentSong(one: Song, other: Song): Boolean = one.title != other.title || one.artist != other.artist


// First, get the songs with tags
songs = songsNtags.vertices

// Then, compute the similarity between each pair of songs with a similarity score larger than 0.7
val similarConnections: RDD[Edge[Double]] = {
    // the computation of the cartesian product is really expensive
    // so we decided to use only the songs with the authors that appears in the final result.
    // NN let's filter before
  val songsWithIndex = songs.filter(x => x._2.tags.size > 5).zipWithIndex
  
  val ss = songsWithIndex.cartesian(songsWithIndex).filter(x => x._1._2 < x._2._2).map(x => (x._1._1,x._2._1)  )
    
//   val ss = songs.cartesian(songs) // this is really expensive to compute, also we do not really need all the matrix
    // since similarity is a simmetric (but not formally a distance because d(x,x) = 1/2 => != 0)
    // so we could think of a method to produce only half of the matrix and excluding directly the diagonal
    // TBC...
    
  // similarSongs are the songs with a similarity score larger than 0.7
  // NN no need to check if they are the same because we have already filtered them using the zipWithIndex
  val similarSongs = ss.filter { x => quiteSimilar(x._1._2, x._2._2, 0.7) }
    
  // Now compute the Jaccard metric for the similarSongs. The result should ba an Edge for each pair of songs
  // with the vertexIds at the two ends, and the Jaccard values as the edge value.
  similarSongs.map { p => {
    val jacIdx = similarity(p._1._2, p._2._2)
    Edge(p._1._1, p._2._1, jacIdx)}
  }
}

val similarByTagsGraph = Graph(songs, similarConnections)
// val similarHighTagsGraph = similarByTagsGraph.subgraph(vpred = (id,attr) => attr.tags.size > 5)
val similarHighTagsGraph = similarByTagsGraph
similarHighTagsGraph.triplets.take(6).foreach(t => println(t.srcAttr + " ~~~ " + t.dstAttr + " => " + t.attr))

Song(Fancy (w\/ T.I. & Swizz Beatz),Drake,Set(rap, wdzh-fm, 2010, hip hop, wjlb-fm, whtd-fm, wkqi-fm)) ~~~ Song(Any Girl (w\/ Lloyd),Lloyd Banks,Set(rap, wdzh-fm, hip hop, wjlb-fm, whtd-fm, wkqi-fm)) => 0.8571428571428571
Song(Roll With It,Easton Corbin,Set(new country, modern country, country, great song, 2010, my favorite)) ~~~ Song(You Lie,The Band Perry,Set(new country, modern country, country, great song, female vocalists, my favorite)) => 0.7142857142857143
Song(Any Girl (w\/ Lloyd),Lloyd Banks,Set(rap, wdzh-fm, hip hop, wjlb-fm, whtd-fm, wkqi-fm)) ~~~ Song(I'm Going In (w\/ Young Jeezy & Lil Wayne),Drake,Set(rap, hip-hop, wdzh-fm, wjlb-fm, whtd-fm, wkqi-fm)) => 0.7142857142857143
Song(While I'm Waiting,John Waller,Set(worship, favorite, christian, contemporary christian, christian rock, mellow)) ~~~ Song(Hold My Heart,Tenth Avenue North,Set(worship, favorite, christian, contemporary christian, christian rock, great)) => 0.7142857142857143
Song(Your Love Is A Song,Switchfoot,Set(

songs = VertexRDDImpl[20] at RDD at VertexRDD.scala:57
similarConnections = MapPartitionsRDD[382] at map at <console>:95
similarByTagsGraph = org.apache.spark.graphx.impl.GraphImpl@1d79ccda
similarHighTagsGraph = org.apache.spark.graphx.impl.GraphImpl@1d79ccda


similarity: (one: Song, other: Song)Double
quiteSimilar: (one: Song, other: Song, threshold: Double)Boolean
differentSong: (one: Song, other: Song)Boolean


org.apache.spark.graphx.impl.GraphImpl@1d79ccda

# HEY IT WORKED!